/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApparelRouteImport } from './routes/apparel'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PartsGearRouteImport } from './routes/parts-gear'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as MountainBikesIndexRouteImport } from './routes/mountain-bikes/index'
import { Route as MountainBikesCategorySlugRouteImport } from './routes/mountain-bikes/$category/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApparelRoute = ApparelRouteImport.update({
  id: '/apparel',
  path: '/apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsGearRoute = PartsGearRouteImport.update({
  id: '/parts-gear',
  path: '/parts-gear',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MountainBikesIndexRoute = MountainBikesIndexRouteImport.update({
  id: '/mountain-bikes/',
  path: '/mountain-bikes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MountainBikesCategorySlugRoute =
  MountainBikesCategorySlugRouteImport.update({
    id: '/mountain-bikes/$category/$slug',
    path: '/mountain-bikes/$category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apparel': typeof ApparelRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/parts-gear': typeof PartsGearRoute
  '/policies': typeof PoliciesRoute
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/wishlist': typeof WishlistRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/mountain-bikes/': typeof MountainBikesIndexRoute
  '/mountain-bikes/$category/$slug': typeof MountainBikesCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apparel': typeof ApparelRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/parts-gear': typeof PartsGearRoute
  '/policies': typeof PoliciesRoute
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/wishlist': typeof WishlistRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/mountain-bikes': typeof MountainBikesIndexRoute
  '/mountain-bikes/$category/$slug': typeof MountainBikesCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/apparel': typeof ApparelRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/parts-gear': typeof PartsGearRoute
  '/policies': typeof PoliciesRoute
  '/search': typeof SearchRoute
  '/service': typeof ServiceRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/wishlist': typeof WishlistRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/mountain-bikes/': typeof MountainBikesIndexRoute
  '/mountain-bikes/$category/$slug': typeof MountainBikesCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/apparel'
    | '/cart'
    | '/checkout'
    | '/parts-gear'
    | '/policies'
    | '/search'
    | '/service'
    | '/sign-in'
    | '/sign-up'
    | '/wishlist'
    | '/guides/$slug'
    | '/mountain-bikes/'
    | '/mountain-bikes/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/apparel'
    | '/cart'
    | '/checkout'
    | '/parts-gear'
    | '/policies'
    | '/search'
    | '/service'
    | '/sign-in'
    | '/sign-up'
    | '/wishlist'
    | '/guides/$slug'
    | '/mountain-bikes'
    | '/mountain-bikes/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/apparel'
    | '/cart'
    | '/checkout'
    | '/parts-gear'
    | '/policies'
    | '/search'
    | '/service'
    | '/sign-in'
    | '/sign-up'
    | '/wishlist'
    | '/guides/$slug'
    | '/mountain-bikes/'
    | '/mountain-bikes/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  ApparelRoute: typeof ApparelRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  PartsGearRoute: typeof PartsGearRoute
  PoliciesRoute: typeof PoliciesRoute
  SearchRoute: typeof SearchRoute
  ServiceRoute: typeof ServiceRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WishlistRoute: typeof WishlistRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  MountainBikesIndexRoute: typeof MountainBikesIndexRoute
  MountainBikesCategorySlugRoute: typeof MountainBikesCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apparel': {
      id: '/apparel'
      path: '/apparel'
      fullPath: '/apparel'
      preLoaderRoute: typeof ApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts-gear': {
      id: '/parts-gear'
      path: '/parts-gear'
      fullPath: '/parts-gear'
      preLoaderRoute: typeof PartsGearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mountain-bikes/': {
      id: '/mountain-bikes/'
      path: '/mountain-bikes'
      fullPath: '/mountain-bikes/'
      preLoaderRoute: typeof MountainBikesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mountain-bikes/$category/$slug': {
      id: '/mountain-bikes/$category/$slug'
      path: '/mountain-bikes/$category/$slug'
      fullPath: '/mountain-bikes/$category/$slug'
      preLoaderRoute: typeof MountainBikesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  ApparelRoute: ApparelRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  PartsGearRoute: PartsGearRoute,
  PoliciesRoute: PoliciesRoute,
  SearchRoute: SearchRoute,
  ServiceRoute: ServiceRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WishlistRoute: WishlistRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  MountainBikesIndexRoute: MountainBikesIndexRoute,
  MountainBikesCategorySlugRoute: MountainBikesCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
